run_arg:
    - --privileged
    - -e DISPLAY=
    - -e TERM=xterm-256color
    - -v /tmp/.X11-unix:/tmp/.X11-unix:ro
    - -v /dev:/dev
    - --network host
build_arg: []
mount_pwd: true
default_shell: zsh
lastexecid: 3a7c7e9a2af7
