run_arg:
    - --privileged
    - -e DISPLAY=:0
    - -e TERM=xterm-256color
    - -v /tmp/.X11-unix:/tmp/.X11-unix:ro
    - -v /dev:/dev
    - --network host
build_arg:
    - --build-arg UID=1001
    - --build-arg GID=1001
mount_pwd: true
default_shell: zsh
lastexecid: 
